collision_alpha: 0.1
collision_size: 1.0
collision_zone_alpha: 0.075
collision_zone_base_diameter: 0.025
color_scheme:
  drl: tab:blue
  drl_spatial_horizon: tab:blue
  dwa: tab:green
  dwa_spatial_horizon: tab:green
  ego: tab:grey
  ego_spatial_horizon: tab:grey
  mpc: tab:red
  mpc_spatial_horizon: tab:red
  rlca: tab:purple
  rlca_spatial_horizon: tab:purple
  teb: tab:orange
  teb_spatial_horizon: tab:orange
goal_marker: '*'
goal_point_color: tab:brown
goal_size: 20
labels:
  drl: DRL
  drl_spatial_horizon: DRL Spatial Horizon
  dwa: DWA
  dwa_spatial_horizon: DWA Spatial Horizon
  ego: EGO
  ego_spatial_horizon: EGO Spatial Horizon
  mpc: MPC
  mpc_spatial_horizon: MPC Spatial Horizon
  rlca: RLCA
  rlca_spatial_horizon: RLCA Spatial Horizon
  teb: TEB
  teb_spatial_horizon: TEB Spatial Horizon
leave_out_metric:
- cusps
leave_out_planner:
- rlca_subsampling
- drl_subsampling
most_recent_file: data_21-11-17_16:31:00.json
obstacle_color: black
obstacle_radius: 0.3
path_alpha: 0.3
path_arrow_color: black
path_arrow_size: 5
path_size: 0.1
plot_barplot_alpha: 1.0
plot_barplot_capsize: 10
plot_barplot_errorcolor: black
plot_barplot_width: 0.5
plot_collision_zones: true
plot_collisions: true
plot_progression: false
plot_qualitative: true
plot_qualitative_axes: true
plot_qualitative_axes_size: 8
plot_qualitative_legend: true
plot_qualitative_legend_location: upper left
plot_qualitative_title: true
plot_qualitative_title_size: 16
plot_quantitative: true
plot_quantitative_axes_label_size: 12
plot_quantitative_axes_tick_size: 10
plot_quantitative_labels:
  angle_over_length: Angle over Length
  collision: Collisions
  computation_time: Computation Time in [s]
  cusps: Cusps
  jerk: Movement Jerk in [$\frac{m}{s^{3}}$]
  max_clearing_distance: Max. Clearing Distance in [m]
  max_curvature: Max. Curvature
  mean_clearing_distance: Mean Clearing Distance in [m]
  median_clearing_distance: Median Clearing Distance in [m]
  min_clearing_distance: Min. Clearing Distance in [m]
  normalized_curvature: Normalized Curvature
  path_length: Path Length in [m]
  planner: Planner
  roughness: Path Roughness
  success: Success, Collision and Timeout Rate
  time: Time Traveled in [s]
plot_quantitative_suptitle: true
plot_quantitative_suptitle_size: 16
plot_quantitative_title: true
plot_quantitative_title_size: 10
plot_quantitative_violin: true
plot_quantitative_violin_inner: point
plot_quantitative_ygrid: true
plot_success_alpha: 1.0
plot_success_collision_color: red
plot_success_legend: true
plot_success_legend_location: upper left
plot_success_success_color: green
plot_success_time_out_color: blue
plot_success_width: 0.5
progression_size: 3
progression_steps: 20
specified_data_filename: null
specify_data: false
start_marker: ^
start_point_color: tab:grey
start_size: 20
